### ISSUE TITLE
TransitionLayer

### ISSUE THREAD

**Issue by tscohen** [t-hanya/chainer-DenseNet#1]
In the original implementation, the transition layer uses 1x1 convolutions and no padding, while this implementation uses 3x3 convolutions with pad=1. This adds a lot of parameters, because the transition layers have many input and output feature maps.

**Comment by t-hanya** [comment]
Thank you very much for your comment @tscohen. I have fixed the implementation of TransitionLayer. I'll train it again, and will update the sample result on README.
